1.
BEGIN;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SHOW TRANSACTION ISOLATION LEVEL;

2.
BEGIN;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SHOW TRANSACTION ISOLATION LEVEL;

1.
SELECT * FROM pizzeria; --  up to date
2.
UPDATE pizzeria SET rating = 3.6 WHERE name = 'Pizza Hut';
COMMIT;

1.
SELECT * FROM pizzeria; -- updated data 3.6
COMMIT
SELECT * FROM pizzeria; -- still updated 3.6